# This is a basic workflow to help you get started with Actions

name: CiCd

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Installing Node
        uses: actions/setup-node@v2-beta
        with:
          node-version: 12
          
          
      - name: Installing yarn
        uses: borales/actions-yarn@v2.0.0
        with:
         cmd: install 
          
     # Build react app
      - name: Build React App
        run: yarn build
        
      - name: Instaling surge
        run: npm install --global surge
        
      - name: deploying using surge
        run: surge ./build oval-wind.surge.sh --token ${{ secrets.SURGE_TOKEN }}    
